name: musicplayer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sleek_circular_slider: ^2.0.0
  flutter_visualizers: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - Assets/

  fonts:
    - family: Lima
      fonts:
        - asset: Assets/Lima Bosonto Unicode.ttf

    - family: Poppins
      fonts:
        - asset: Assets/Poppins-Regular.ttf

